---
title: "Tetiaroa Data Trust Policy"
author: "Tetiaroa Society, French Polynesia"
date: 'Last edited: 2025-08-22 | V1.0.0 (presented to the Tetiaroa Society Board)'
output: html_document
---

------------------------------------------------------------------------

*Tl;dr In return for the support and access to Tetiaroa (the physical island, material samples, and derived data) provided by Tetiaroa Society, participants in research projects agree to make their metadata and prepublication data available to each other through a “Tetiaroa Data Trust” that facilitates data and material sample re-use according to mutually agreed terms and a code of conduct. The Trust is maintained by the Tetiaroa Society to support decision-making for wise and equitable stewardship of the atoll. It follows best practices in research data stewardship. This policy does not impose legally binding conditions nor replace or impinge on legal obligations that might apply elsewhere.*

This is a living document. Ideas or feedback can be contributed through this form: <https://forms.gle/7aGfkZndD5bmkGrw7>

------------------------------------------------------------------------

## Preamble

The owners of Tetiaroa have entrusted Tetiaroa Society (hereinafter “the Society”) as the atoll’s environmental steward with authority to develop and implement the **Tetiaroa Conservation & Sustainable Use Plan**[^1] (hereinafter “CASUP”), and to manage access to the atoll for research, education, or conservation projects (hereinafter “Projects). Projects must be authorized by Tetiaroa Society with advice from its Scientific Advisory Board (SAB), Cultural Advisory Board (CAB), and/or other bodies, as appropriate. To ensure the responsible stewardship of data and other outputs derived from Projects (including material samples and intellectual property) Tetiaroa Society has established a data trust, which provides independent, fiduciary stewardship of data related to Tetiaroa[^2]. The **Tetiaroa Data Trust** is a source of admissible evidence informing policy and management decisions (CASUP); it facilitates the development of tools that leverage AI and Digital Twin technologies to support scenario-based planning (see Tetiaroa IDEA[^3]).

[^1]: Tetiaroa Society. (2016). Tetiaroa Conservation & Sustainable Use Plan. Tetiaroa Society. <https://doi.org/10.5281/zenodo.16969285>

[^2]: Hardinges (2020) Open Data Institute. <https://theodi.org/news-and-events/blog/data-trusts-in-2020/>

[^3]: Tetiaroa Society is a collaborating node of the IDEA Consortium, simulating future states of social-ecological systems under alternative scenarios of human activity and/or environmental change.

## Purpose of this Document

The current document (hereinafter “the Policy”) represents guidelines that define the terms under which Tetiaroa Society grants Projects access to Tetiaroa and the expectations Tetiaroa Society has for Projects to contribute to the Tetiaroa Data Trust. The document is intended to be ‘socially binding’ with respect to the principles and common understanding described herein. The Policy does not preclude or replace legal obligations or responsibilities that project participants or institutions might incur (e.g., under the regulations and laws of French Polynesia).  

## Article 1 -- Convention

1.  Tetiaroa is committed to the wise stewardship of the atoll as described in the **Tetiaroa Conservation & Sustainable Use Plan**

2.  In return for the permission and support provided by **Tetiaroa Society** to access the atoll, participants in Projects agree to contribute to the **Tetiaroa Data Trust,** to participate in the **Tetiaroa IDEA**, and abide by the **IDEA Consortium Code of Conduct** (see **Exhibit 1)**.

3.  Project leaders (hereinafter “Principal Investigators” or “PIs”) agree to submit an application describing their Project to Tetiaroa Society and commit to data and material sample management procedures (see **Exhibit 2** for current procedures).  

4.  Principal Investigators agree that Tetiaroa Society may publish a document drawing on their project application as an Open Access[^4] **Marker Paper**[^5], attributing the PIs. 

5.  Principal Investigators agree to make all reasonable efforts to connect the Marker Paper to derived outputs of the Project, utilizing and maintaining persistent identifiers and linkages generated through their work on Tetiaroa.

6.  Tetiaroa Society may make a **Data Dashboard** available as an Open Access portal to Project metadata and links to Project outputs.

[^4]: Policy guidelines for the development and promotion of open access UNESCO (2012) <https://unesdoc.unesco.org/ark:/48223/pf0000215863>

[^5]: Peterson, J., Campbell, J. Marker papers and data citation. Nat Genet 42, 919 (2010). <https://doi.org/10.1038/ng1110-919>

## Article 2 -- Contributors and Users 

1.  The Tetiaroa Data Trust consists primarily of the body of digital data and knowledge, including scientific, social, and legal metadata, contributed by Projects carried out in situ on Tetiaroa under the terms of this Policy. 

2.  The Data Trust may also include contributions of scientific models, software, or ex situ data (data generated about Tetiaroa without physical access to the atoll) that are not necessarily subject to the terms of this Policy. Access to these resources may therefore be subject to specific terms agreed with their contributors.

3.  Users wishing to access digital resources in the Data Trust that are not available to them under Open Access, or other terms, may submit a Project application to Tetiaroa Society[^6]. 

[^6]: Access to the “digital Tetiaroa” is under similar terms to projects requesting physical access.

## Article 3 -- Ethical, Legal, and Social Responsibility 

1.  Certain data types or samples may require special consideration for ethical, legal, and/or social reasons (including privacy and commercial confidentiality). Examples might include, but are not limited to, data or samples associated with traditional knowledge, archeological artifacts, endangered species, medical data, and human subject research. In some cases, government permits might be required. In other cases, there might be commercial considerations and/or social contexts where consent should be obtained. These aspects should be considered and addressed in the Project application.

2.  Requests to deviate from the terms described in this Policy should be submitted to Tetiaroa Society with justification in the Project application, or subsequently if new issues arise.

## Article 4 -- Commercial Projects

1.  Projects with commercial intent require a Project-specific agreement with Tetiaroa Society. 

2.  Commercial use is defined here as the sale, lease, or license of Project outputs; using the outputs to produce or manufacture products for general sale, not including publications and/or copyrightable works; transferring tangible rights by sale or license resulting in payment beyond cost; conducting market research; seeking pre-market approval.

3.  Projects may start with non-commercial intent but subsequently wish to begin commercial activities. In such circumstances, the Principal Investigator shall request a new agreement with Tetiaroa Society prior to carrying out any commercial activity.

## Article 5 -- Dispute Resolution

1.  Disputes concerning the use of data or samples in ways that breach the good-faith engagements made under this Policy are adjudicated by Tetiaroa Society with input from its Advisory Boards and other bodies as appropriate. Sanctions for failing to comply with the IDEA Code of Conduct or other aspects of the Policy may include the rescinding of rights of future access to Tetiaroa.

2.  This dispute resolution mechanism does not cover breaches of applicable laws or regulations, which shall be dealt with by the competent authorities.

## Article 6 -- Financial Aspects

1.  Nothing in this document commits Tetiaroa Society or any other parties financially.

## Article 7 -- Compliance Monitoring 

1.  The Tetiaroa Society will identify a delegate to check compliance with the Policy

# Acknowledgements

# Exhibit 1 -- IDEA Code of Conduct

The following is adapted from the Toronto Statement on Prepublication International Data Sharing. [^7]

[^7]:  [**Prepublication data sharing**](https://www.nature.com/nature/journal/v461/n7261/full/461168a.html) Toronto International Data Release Workshop Authors Nature **461**, 168-170 (10 September 2009) <doi:10.1038/461168a>

------------------------------------------------------------------------

\
Participants in the IDEA Consortium agree to abide by the following principles:\

**Respect the Privacy, Ethical, and Legal rights** of anyone, including Indigenous peoples[^8], who might be adversely affected by the collection, distribution, use or reuse of data, samples or derived information and knowledge. Apply consent, confidentiality, anonymization and other ethical considerations, where appropriate.

[^8]: Collective benefit, Authority to control, Responsibility, and Ethics - CARE principles for Indigenous data governance. GIDA h[ttps://www.Gida-Global.Org/care](https://www.gida-global.org/care)

**Rapid prepublication data release to** the IDEA Consortium (e.g., through one of its regional chapters such as the Tetiaroa IDEA), which is a program with the following characteristics:

-   Large scale (requiring significant resources over time) and broad utility

-   Creating reference data sets

-   Associated with community buy-in

**Coordinating nodes** (e.g., Tetiaroa Society for the Tetiaroa IDEA)shouldfacilitate the specification of data-release policies and compliance with agreed Data Management Plans by:

-   Explicitly informing applicants of data-release requirements, especially mandatory prepublication data release 

-   Ensuring that evaluation of data release plans is part of the peer-review process 

-   Proactively establishing analysis plans and timelines for projects releasing data prepublication

-   Fostering investigator-initiated prepublication data release

-   Helping to develop appropriate consent, security, access and governance mechanisms that protect research participants while encouraging prepublication data release

-   Providing long-term support of databases

**Project leaders** should state their intentions and enable analyses of their data or material samples by:

-   Informing data/sample users (e.g., through a 'marker paper' at initiation of the project) about the data/samples being generated, data standards and quality, planned analyses, timelines, and relevant contact information

-   Providing relevant metadata and documentation that will assist other researchers in reproducing and/or independently analyzing the data, while protecting privacy and other ethical, legal, and social aspects concerning individuals and communities

-   Ensuring that all participants in their Project are informed that their data will be shared with other scientists in the IDEA Consortium and the associated terms

-   Publishing their initial global analyses in a timely fashion

-   Providing a copy of their data, protocols, software and other outputs, in an easily retrievable form and with appropriate metadata and documentation that facilitates usage of both pre-processed and processed data (e.g., following FAIR data principles) 

-   Ensuring the long-term maintenance of these resources (e.g., through deposition in appropriate repositories and collections).

**Data analysts/users** should freely analyze released prepublication data or samples and act responsibly in publishing their analyses by:

-   Respecting the scientific etiquette that allows data producers to publish the first global analyses of their data set 

-   Reading the citable document(s) associated with the project (e.g., 'marker paper')

-   Accurately and completely citing the source of prepublication data and metadata, including the version of the data set 

-   Being aware that released prepublication data may be associated with quality issues that will be later rectified by the data producers

-   Contacting the data producers to discuss publication plans in the case of overlap between planned analyses

-   Ensuring that use of data does not harm participants and is in conformity with ethical, legal, and social aspects and approvals

-   In case of major data project using substantial, significant or otherwise potentially sensitive prepublication data, users are encouraged to submit a Project application to TS for access to the data (digital Tetiaroa) to facilitate review and collaboration with relevant stakeholders

# Exhibit 2 -- Material Samples

------------------------------------------------------------------------

1.  Each project's DMP shall include a description of the physical collection and removal (extraction) of material samples from Tetiaroa - whether archeological, geological/chemical, biological, or social (built environment). Projects shall describe in their DMP how they plan to register these sampling events, apply unique identifiers, implement relevant metadata standards, and track derived material (sub)samples, (meta)data, and other derived outputs. 

2.  In the case of biological samples, the Tetiaroa Society has established the **Tetiaroa Biocode & Genomic Observatory**, a scientific research program with the following objectives: 

    a.  to comprehensively inventory the biodiversity of Tetiaroa, including all species of fauna and flora -- plants, animals, algae, fungi, and microbial groups;
    b.  to generate time-series biodiversity observations at the bio-molecular level, including nucleotide sequencing and other "multi-omic" approaches[^9]. 
    c.  to test new technological and scientific approaches for the analysis of biodiversity patterns and ecological processes in general; and to make material samples and information available to the research community. 

3.  In accordance with the Convention on Biological Diversity (Nagoya Protocol) and associated regulations of the French Polynesian government, all biosamples collected on Tetiaroa contribute to the Tetiaroa Biocode & Genomic Observatory and shall comply with the "[Tetiaroa Access & Benefit Sharing (ABS) Agreement](https://drive.google.com/open?id=1W0SK1YihP2eHkt7WhOwJBp5mhy7o1HBx)" 

[^9]:  Davies et al. Founding Charter of the Genomic Observatories Network. GigaScience 2014, <http://www.gigasciencejournal.com/content/3/1/2>
